export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const LOCALHOST = 'localhost';
export const LOCAL_DEVELOPMENT = 'local_development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const GLOBAL_REPOSITORY = 'GLOBAL_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const REDEMPTIONS_REPOSITORY = 'REDEMPTIONS_REPOSITORY';
export const REDEMPTIONS_TYPES_TICKETS_REPOSITORY =
  'REDEMPTIONS_TYPES_TICKETS_REPOSITORY';
export const REDEMPTIONS_TYPES_REPOSITORY = 'REDEMPTIONS_TYPES_REPOSITORY';
export const SUBSCRIPTION_REPOSITORY = 'SUBSCRIPTION_REPOSITORY';
export const USER_TICKET_REPOSITORY = 'USER_TICKET_REPOSITORY';
export const TICKET_REPOSITORY = 'TICKET_REPOSITORY';
export const TICKET_DEPENDENCIES_REPOSITORY = 'TICKET_DEPENDENCIES';
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const PAYMENT_TICKET_REPOSITORY = 'PAYMENT_TICKET_REPOSITORY';
export const USER_TICKETS_PREFERENCES_REPOSITORY =
  'USER_TICKETS_PREFERENCES_REPOSITORY';
export const PREFERENCES_REPOSITORY = 'PREFERENCES_REPOSITORY';
export const USERS_PREFERENCES_REPOSITORY = 'USERS_PREFERENCES_REPOSITORY';
